### ISSUE TITLE
Update README for OS X

### ISSUE THREAD

**Issue by noloader** [scito/extract_otp_secrets#186]
Hi Everyone,

The README currently states:

> 
> However, the bare executable can be executed from the command line:
> 
>     1. Download executable for macOS platform from [latest release](https://github.com/scito/extract_otp_secrets/releases/latest), see assets
>     2. Open Terminal application
>     3. Change to Downloads folder in Terminal: cd $HOME/Downloads
>     4. Set executable bit for the downloaded file: chmod +x extract_otp_secrets_X.Y.Z_macos_x86_64
>     5. Start executable from command line: ./extract_otp_secrets_X.Y.Z_macos_x86_64

After step (4), I believe you should recommend (require?) `xattr -r -d com.apple.quarantine extract_otp_secrets_X.Y.Z_macos_x86_64`. Otherwise, Apple may still keep it in quarantine and not allow it to execute.

Also see <https://github.com/scito/extract_otp_secrets/pull/187>.

**Comment by scito** [comment]
Fixed with #187

Thanks a lot!
