### ISSUE TITLE
Export in URI format

### ISSUE THREAD

**Issue by signetica** [scito/extract_otp_secrets#196]
It would be very helpful to be able to export the URIs from a google export, so that they could be imported in a batch into FreeOTP+ or other authenticators that accept lists of URIs.  As it is, I think the only way to do this is to export the QR codes for each entity, then extract the URIs from those with a camera.

Thanks in any case for this very useful project.

**Comment by scito** [comment]
Can you give an example of such a list of URIs?
Is this a list of each key?

**Comment by scito** [comment]
Example of url list:

```
otpauth://totp/pi%40raspberrypi?secret=7KSQL2JTUDIS5EF65KLMRQIIGY&issuer=raspberrypi
otpauth://totp/pi%40raspberrypi?secret=7KSQL2JTUDIS5EF65KLMRQIIGY
otpauth://totp/pi%40raspberrypi?secret=7KSQL2JTUDIS5EF65KLMRQIIGY
otpauth://totp/pi%40raspberrypi?secret=7KSQL2JTUDIS5EF65KLMRQIIGY&issuer=raspberrypi
otpauth://hotp/hotp%20demo?secret=7KSQL2JTUDIS5EF65KLMRQIIGY&counter=4
otpauth://totp/encoding%3A%20%C2%BF%C3%A4%C3%84%C3%A9%C3%89%3F%20%28demo%29?secret=7KSQL2JTUDIS5EF65KLMRQIIGY
```

@signetica Is this list of urls what you wish?

**Comment by signetica** [comment]
Yes, that's exactly what I needed.  I was able to produce it  from the .json format by running  the .json output through sed -n -e '/^ *"url"/s/.*\(otpauth.*\)"$/\1/p'.  The list of  URLs is what most of the other authenticator apps I've used need for import, and it's great that your program can produce it now.

Thanks very much for your work.

**Comment by signetica** [comment]
Ok, I've tested the commit and it worked perfectly.  Thanks very much for this useful addition.

**Comment by scito** [comment]
Thanks for your suggestion and thanks for your testing!
