### ISSUE TITLE
OTPs not being read from QR code images

### ISSUE THREAD

**Issue by zachariapopcorn** [scito/extract_otp_secrets#210]
When I try to extract keys from an image of the QR code, it says that it extracted 0 otps

This worked before so I'm unsure on why it's not working now

**Comment by scito** [comment]
I tried again and it still works for me.
It need more information for reproduction of your problem. Please write the steps. Additionally I need also the versions.

**Comment by scito** [comment]
Not feedback, please reopen if still relevant
