### ISSUE TITLE
File name wildcards don't work on Windows

### ISSUE THREAD

**Issue by kuro68k** [scito/extract_otp_secrets#328]
When trying to use wildcards in file names, as shown in the examples, I get an error message:

```
> extract_otp_secrets_2.8.4_win_x86_64.exe *jpg
ERROR: Input file provided is non-existent or not a file.
input file: *.jpg
```

There are valid .jpg files in the same directory and they decode okay individually.

**Comment by scito** [comment]
@kuro68k Thanks for your report. This feature was missing. On Linux, the shell was doing the expansion. I've implemented in extract_otp_secrets script. Can you test?

**Comment by kuro68k** [comment]
@scito Can confirm that it works well. Thank you very much.
