### ISSUE TITLE
Installation of zbar with Archlinux

### ISSUE THREAD

**Issue by mastromberger** [scito/extract_otp_secrets#43]
Hi
Can you please add follwing to Installation of shared system libraries for Archlinux?
pacman -S zbar

Without zbar I've got following
python src/extract_otp_secrets.py example_export.txt

ERROR: Cannot import QReader module. This problem is probably due to the missing zbar shared library.
On Linux and macOS libzbar0 must be installed.
See in README.md for the installation of the libzbar0.
Exception: Unable to find zbar shared library

After the command "pacman -S zbar" everything worked fine

greetings
Martin Stromberger

**Comment by scito** [comment]
Thanks for your input! I've added it for Arch Linux.
