### ISSUE TITLE
windows executable fails

### ISSUE THREAD

**Issue by flowirin** [scito/extract_otp_secrets#69]
after the unsigned warning, the thing just doesn't open

also, where is the original extract .py file? i'd be happy using that

**Comment by scito** [comment]
> after the unsigned warning, the thing just doesn't open

I cannot reproduce the problem. I'm running Windows 10 22H2 with 
extract_otp_secrets_2.4.1_win_x86_64.exe  without any problems.

Can you open a terminal and run the exe from there? Maybe there are helpful error messages.

> also, where is the original extract .py file? i'd be happy using that

Use either
https://github.com/scito/extract_otp_secrets#installation-of-python-script-recommended-for-developers-or-advanced-users
or
https://github.com/scito/extract_otp_secrets#alternative-installation-methods

**Comment by aaronshenhao** [comment]
Same problem with latest version. Might have to just build the Docker image myself.
