### ISSUE TITLE
ERROR: Cannot decode otpauth-migration migration payload.

### ISSUE THREAD

**Issue by zdary** [scito/extract_otp_secrets#72]
exporting from recent version of google authenticator the process fails
ERROR: Cannot decode otpauth-migration migration payload.

**Comment by scito** [comment]
I'm using latest version of Google Authenticator Version (5.20R4) and I do not have any problems extracting the secrets.

Which version of Google Authenticator are you using?
Are you extracting directly from camera or from file?
What are the steps to reproduce the problem? (Maybe you can use a test entry.)

Can you try re-run in debug mode? Use parameter `-vvv`

```shell
./extract_otp_secrets -vvv
```

Can you provide the debug output? (Note: Remove any secret information form debug output.)
